version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: protaxo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lizaliza123
      POSTGRES_DB: protaxo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: protaxo_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata: