
ALTER TABLE invoices ADD COLUMN vehicle_name VARCHAR(255);
ALTER TABLE invoices ADD COLUMN driver_name VARCHAR(255);
ALTER TABLE invoices ADD COLUMN transport_responsible_name VARCHAR(255);
ALTER TABLE invoices ADD COLUMN repair_supervisor_name VARCHAR(255);

CREATE TABLE field_suggestions (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(30) NOT NULL,
    value    VARCHAR(255) NOT NULL,
    UNIQUE (category, value)
);
