CREATE TABLE catalog_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(20) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    base_price      NUMERIC(12,2) NOT NULL,
    stock_quantity  NUMERIC(12,3),
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP,
    deleted_at      TIMESTAMP
);
