CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(255) NOT NULL,
    action      VARCHAR(20) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id   BIGINT,
    occurred_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_audit_log_occurred_at ON audit_log (occurred_at DESC);
