CREATE TABLE calibration_protocols (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_date             TIMESTAMP NOT NULL,
    internal_number           VARCHAR(50) NOT NULL,
    stamp_number              VARCHAR(50),
    client_id                 BIGINT NOT NULL REFERENCES clients(id),
    vehicle_name              VARCHAR(255),
    card_number               VARCHAR(15) NOT NULL,
    representative_name       VARCHAR(255),
    tachograph_brand          VARCHAR(100),
    tachograph_model          VARCHAR(100),
    tachograph_type           VARCHAR(100),
    tachograph_manufacturer   VARCHAR(100),
    previous_inspection_date  DATE,
    version                   BIGINT NOT NULL DEFAULT 0,
    created_at                TIMESTAMP NOT NULL DEFAULT now(),
    updated_at                TIMESTAMP,
    deleted_at                TIMESTAMP
);

CREATE INDEX idx_calibration_protocols_client_id ON calibration_protocols (client_id);
