CREATE TABLE clients (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,
    edrpou                VARCHAR(20) UNIQUE,
    contacts              VARCHAR(500),
    default_payment_type  VARCHAR(20),
    version               BIGINT NOT NULL DEFAULT 0,
    created_at            TIMESTAMP NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP,
    deleted_at            TIMESTAMP
);
