CREATE TABLE vehicle_makes (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE vehicle_models (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make_id BIGINT NOT NULL REFERENCES vehicle_makes(id),
    name    VARCHAR(100) NOT NULL,
    UNIQUE (make_id, name)
);

CREATE INDEX idx_vehicle_models_make_id ON vehicle_models (make_id);

-- Seed a starter set of common truck manufacturers and models — the catalog is meant to
-- grow over time via the "+ Додати нову марку/модель" modals, this is just a useful start.
INSERT INTO vehicle_makes (name) VALUES
    ('MAN'), ('Mercedes-Benz'), ('Volvo'), ('Scania'), ('DAF'),
    ('Iveco'), ('Renault Trucks'), ('KamAZ'), ('MAZ'), ('ГАЗ');

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('TGX'), ('TGS'), ('TGM'), ('TGL')) AS m(model)
WHERE vehicle_makes.name = 'MAN';

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('Actros'), ('Atego'), ('Axor')) AS m(model)
WHERE vehicle_makes.name = 'Mercedes-Benz';

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('FH'), ('FM'), ('FMX')) AS m(model)
WHERE vehicle_makes.name = 'Volvo';

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('R-series'), ('S-series'), ('P-series'), ('G-series')) AS m(model)
WHERE vehicle_makes.name = 'Scania';

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('XF'), ('CF'), ('LF')) AS m(model)
WHERE vehicle_makes.name = 'DAF';

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('Stralis'), ('Eurocargo'), ('Daily')) AS m(model)
WHERE vehicle_makes.name = 'Iveco';

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('T'), ('D'), ('K'), ('C')) AS m(model)
WHERE vehicle_makes.name = 'Renault Trucks';

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('5490'), ('65115'), ('43118')) AS m(model)
WHERE vehicle_makes.name = 'KamAZ';

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('5440'), ('6501'), ('4370')) AS m(model)
WHERE vehicle_makes.name = 'MAZ';

INSERT INTO vehicle_models (make_id, name)
SELECT id, model FROM vehicle_makes CROSS JOIN LATERAL (VALUES ('3307'), ('33086'), ('С41R13')) AS m(model)
WHERE vehicle_makes.name = 'ГАЗ';
