CREATE TABLE vehicles (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id             BIGINT NOT NULL REFERENCES clients(id),
    vin                   VARCHAR(32) NOT NULL UNIQUE,
    registration_number   VARCHAR(20) NOT NULL,
    make                  VARCHAR(100),
    model                 VARCHAR(100),
    year                  INTEGER,
    version               BIGINT NOT NULL DEFAULT 0,
    created_at            TIMESTAMP NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP,
    deleted_at            TIMESTAMP
);

CREATE INDEX idx_vehicles_client_id ON vehicles (client_id);
