-- Two small reference catalogs for the calibration protocol form:
-- master_cards backs the "Номер картки" picker (workshop master cards, each with a holder),
-- tachograph_attributes backs the "Дані тахографа" dropdowns (марка/модель/тип/виробник) —
-- one shared table with a category discriminator, same pattern as field_suggestions, but a
-- "hard" managed list (real dropdown + add-modal) rather than free-text autocomplete.

CREATE TABLE master_cards (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number  VARCHAR(20) NOT NULL UNIQUE,
    holder_name  VARCHAR(255) NOT NULL
);

CREATE TABLE tachograph_attributes (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(20) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    UNIQUE (category, name)
);
