CREATE TABLE role_permissions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role           VARCHAR(20) NOT NULL UNIQUE,
    permissions    TEXT NOT NULL,
    version        BIGINT NOT NULL DEFAULT 0,
    created_at     TIMESTAMP NOT NULL DEFAULT now(),
    updated_at     TIMESTAMP,
    deleted_at     TIMESTAMP
);

-- ADMIN завжди має повний доступ у коді (PermissionService), цей рядок лише для
-- одноманітності — не читається як джерело правди для ADMIN.
INSERT INTO role_permissions (role, permissions) VALUES
    ('ADMIN', '{"canViewAuditLog": true, "canManageUsers": true}'),
    ('MASTER', '{"canViewAuditLog": false, "canManageUsers": false}');
