CREATE TABLE contracts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         BIGINT NOT NULL REFERENCES clients(id),
    contract_number   VARCHAR(50) NOT NULL UNIQUE,
    status            VARCHAR(20) NOT NULL,
    version           BIGINT NOT NULL DEFAULT 0,
    created_at        TIMESTAMP NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP,
    deleted_at        TIMESTAMP
);

CREATE INDEX idx_contracts_client_id ON contracts (client_id);
