-- Фінансовий облік (docs/Фінансовий облік.md): каси/рахунки, фінансові операції, звірки,
-- ПДВ по позиціях каталогу й наряду, ознака "платник ПДВ" у контрагента, строк оплати наряду.

-- ---------------------------------------------------------------- ПДВ
-- Ціна вводиться З ПДВ; ставка береться з позиції каталогу й копіюється в рядок наряду,
-- щоб пізніша зміна каталогу не переписувала вже виставлені документи.
ALTER TABLE catalog_items ADD COLUMN vat_rate VARCHAR(10) NOT NULL DEFAULT 'VAT_20';

ALTER TABLE invoice_items ADD COLUMN vat_rate VARCHAR(10) NOT NULL DEFAULT 'VAT_20';
ALTER TABLE invoice_items ADD COLUMN vat_amount NUMERIC(14,2);
ALTER TABLE invoice_items ADD COLUMN amount_without_vat NUMERIC(14,2);

-- Існуючі рядки: те саме правило, що досі застосовувалось лише під час друку PDF рахунку
-- (20/120 від суми рядка, HALF_UP до копійок) — ROUND у Postgres для numeric округлює
-- половину від нуля, для додатних сум це HALF_UP.
UPDATE invoice_items SET vat_amount = ROUND(amount * 20 / 120, 2);
UPDATE invoice_items SET amount_without_vat = amount - vat_amount;
ALTER TABLE invoice_items ALTER COLUMN vat_amount SET NOT NULL;
ALTER TABLE invoice_items ALTER COLUMN amount_without_vat SET NOT NULL;

ALTER TABLE clients ADD COLUMN vat_payer BOOLEAN NOT NULL DEFAULT FALSE;

-- Строк оплати наряду: прострочення визначається окремо від стану оплати.
ALTER TABLE invoices ADD COLUMN payment_due_date DATE;

-- ---------------------------------------------------------------- Каси й рахунки
CREATE TABLE finance_accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    kind             VARCHAR(20)  NOT NULL,
    opening_balance  NUMERIC(14,2) NOT NULL DEFAULT 0,
    active           BOOLEAN NOT NULL DEFAULT TRUE,
    version          BIGINT NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ,
    deleted_at       TIMESTAMPTZ
);

INSERT INTO finance_accounts (name, kind) VALUES
    ('Каса', 'CASH'),
    ('Банківський рахунок', 'BANK'),
    ('Картковий термінал', 'CARD');

-- ---------------------------------------------------------------- Звірки
CREATE TABLE finance_reconciliations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          BIGINT NOT NULL REFERENCES finance_accounts(id),
    counted_at          TIMESTAMPTZ NOT NULL,
    expected_balance    NUMERIC(14,2) NOT NULL,
    actual_balance      NUMERIC(14,2) NOT NULL,
    difference          NUMERIC(14,2) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    comment             TEXT,
    created_by          VARCHAR(255) NOT NULL,
    resolved_at         TIMESTAMPTZ,
    resolved_by         VARCHAR(255),
    resolution_comment  TEXT,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    deleted_at          TIMESTAMPTZ
);

CREATE INDEX idx_finance_reconciliations_status ON finance_reconciliations (status);

-- ---------------------------------------------------------------- Операції
-- Один журнал для всіх рухів коштів: оплата, повернення, витрата, переміщення, внесення/
-- вилучення власником, коригування за звіркою. amount завжди > 0, напрям визначається типом.
-- Проведені операції не видаляються: скасування (сторно) ставить cancelled_* з причиною,
-- і операція перестає впливати на залишки й борги, але лишається в історії.
CREATE TABLE finance_operations (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                   VARCHAR(30) NOT NULL,
    account_id             BIGINT NOT NULL REFERENCES finance_accounts(id),
    target_account_id      BIGINT REFERENCES finance_accounts(id),
    amount                 NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    payment_method         VARCHAR(20),
    invoice_id             BIGINT REFERENCES invoices(id),
    original_operation_id  BIGINT REFERENCES finance_operations(id),
    reconciliation_id      BIGINT REFERENCES finance_reconciliations(id),
    received_amount        NUMERIC(14,2),
    change_amount          NUMERIC(14,2),
    refund_kind            VARCHAR(30),
    expense_category       VARCHAR(30),
    counterparty           VARCHAR(255),
    document_ref           VARCHAR(255),
    comment                TEXT,
    occurred_at            TIMESTAMPTZ NOT NULL,
    created_by             VARCHAR(255) NOT NULL,
    request_key            VARCHAR(64) NOT NULL UNIQUE,
    cancelled_at           TIMESTAMPTZ,
    cancelled_by           VARCHAR(255),
    cancel_reason          TEXT,
    version                BIGINT NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ,
    deleted_at             TIMESTAMPTZ
);

CREATE INDEX idx_finance_operations_invoice_id ON finance_operations (invoice_id);
CREATE INDEX idx_finance_operations_account_id ON finance_operations (account_id);
CREATE INDEX idx_finance_operations_occurred_at ON finance_operations (occurred_at DESC);
CREATE INDEX idx_finance_operations_original ON finance_operations (original_operation_id);

-- Підтвердний документ до витрати (скан чека, накладна). Окрема таблиця, щоб байти файлу
-- не вантажились разом з кожною операцією в списках.
CREATE TABLE finance_attachments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id   BIGINT NOT NULL REFERENCES finance_operations(id),
    file_name      VARCHAR(255) NOT NULL,
    content_type   VARCHAR(100) NOT NULL,
    size_bytes     BIGINT NOT NULL,
    data           BYTEA NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_finance_attachments_operation_id ON finance_attachments (operation_id);
