-- Ревізія складу (docs/Ревізія складу.md): перерахунок фактичних залишків товарів каталогу.
-- Чернетка знімає перелік товарів з поточними залишками; під час проведення облікова кількість
-- перезнімається на момент проведення, різниця фіксується, а залишок у каталозі стає фактичним.

CREATE TABLE stock_revisions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status        VARCHAR(20) NOT NULL,
    comment       TEXT,
    created_by    VARCHAR(255) NOT NULL,
    completed_at  TIMESTAMPTZ,
    completed_by  VARCHAR(255),
    version       BIGINT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ,
    deleted_at    TIMESTAMPTZ
);

CREATE TABLE stock_revision_items (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id        BIGINT NOT NULL REFERENCES stock_revisions(id) ON DELETE CASCADE,
    catalog_item_id    BIGINT NOT NULL REFERENCES catalog_items(id),
    item_name          VARCHAR(255) NOT NULL,
    expected_quantity  NUMERIC(12,3) NOT NULL,
    actual_quantity    NUMERIC(12,3),
    difference         NUMERIC(12,3),
    unit_price         NUMERIC(12,2),
    comment            VARCHAR(255)
);

CREATE INDEX idx_stock_revision_items_revision_id ON stock_revision_items (revision_id);
