CREATE TABLE drivers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    BIGINT NOT NULL REFERENCES clients(id),
    full_name    VARCHAR(255) NOT NULL,
    phone        VARCHAR(30),
    version      BIGINT NOT NULL DEFAULT 0,
    created_at   TIMESTAMP NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP,
    deleted_at   TIMESTAMP
);

CREATE INDEX idx_drivers_client_id ON drivers (client_id);
