-- Товари, оприбутковані витратою «Запчастини та матеріали»: кожен рядок збільшує залишок
-- позиції каталогу й оновлює її ціну закупівлі; при скасуванні витрати залишок повертається.
CREATE TABLE finance_expense_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id    BIGINT         NOT NULL REFERENCES finance_operations(id),
    catalog_item_id BIGINT         NOT NULL REFERENCES catalog_items(id),
    line_number     INTEGER        NOT NULL,
    item_name       VARCHAR(255)   NOT NULL,
    quantity        NUMERIC(12, 3) NOT NULL,
    purchase_price  NUMERIC(12, 2) NOT NULL,
    amount          NUMERIC(14, 2) NOT NULL,
    created_new     BOOLEAN        NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_finance_expense_items_operation_id ON finance_expense_items (operation_id);
CREATE INDEX idx_finance_expense_items_catalog_item_id ON finance_expense_items (catalog_item_id);
