CREATE TABLE tachographs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id       BIGINT NOT NULL REFERENCES vehicles(id),
    manufacturer     VARCHAR(100) NOT NULL,
    model            VARCHAR(100) NOT NULL,
    firmware_version VARCHAR(50),
    serial_number    VARCHAR(100) NOT NULL UNIQUE,
    production_date  DATE,
    version          BIGINT NOT NULL DEFAULT 0,
    created_at       TIMESTAMP NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP,
    deleted_at       TIMESTAMP
);

CREATE INDEX idx_tachographs_vehicle_id ON tachographs (vehicle_id);
