CREATE TABLE orders (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id            BIGINT NOT NULL REFERENCES clients(id),
    contract_id          BIGINT REFERENCES contracts(id),
    vehicle_id           BIGINT NOT NULL REFERENCES vehicles(id),
    driver_id            BIGINT REFERENCES drivers(id),
    master_id            BIGINT NOT NULL REFERENCES users(id),
    status               VARCHAR(20) NOT NULL,
    calibration_reason   VARCHAR(500),
    payment_type         VARCHAR(20),
    payment_status       VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    version              BIGINT NOT NULL DEFAULT 0,
    created_at           TIMESTAMP NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP,
    deleted_at           TIMESTAMP
);

CREATE INDEX idx_orders_client_id ON orders (client_id);
CREATE INDEX idx_orders_vehicle_id ON orders (vehicle_id);
