CREATE TABLE invoices (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number             VARCHAR(50) NOT NULL,
    document_date      TIMESTAMP NOT NULL,
    organization_name  VARCHAR(255) NOT NULL,
    client_id          BIGINT NOT NULL REFERENCES clients(id),
    version            BIGINT NOT NULL DEFAULT 0,
    created_at         TIMESTAMP NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP,
    deleted_at         TIMESTAMP
);

CREATE TABLE invoice_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id    BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    line_number   INTEGER NOT NULL,
    item_name     VARCHAR(255) NOT NULL,
    quantity      NUMERIC(12,3) NOT NULL,
    price         NUMERIC(12,2) NOT NULL,
    amount        NUMERIC(14,2) NOT NULL
);

CREATE INDEX idx_invoices_client_id ON invoices (client_id);
CREATE INDEX idx_invoice_items_invoice_id ON invoice_items (invoice_id);
